package com.valhallagame.traitserviceclient.message;

public enum TraitType {
	// GIFTS
	KICK,
	DODGE,
	FROST_BLAST,
	GUNGNIRS_WRATH,
	SOUL_TRANSFUSION,
	SHIELD_BASH,
	FROST_ARROWS,
	RECOVER,
	PETRIFY,
	NORTHERN_WINDS,
	SHIELD_BREAKER,
	HEMORRHAGE,
	COUNTERATTACK,
	TAUNT,
	FREYRS_PURGE,
	FRIGGS_INTERVENTION,
	SEIDHRING,

	// CURSES
	POOR_COMBAT_AWARENESS,
	ALZHEIMERS,
	TOURETTES,
	POOR_METABOLISM,
	PARANOIA
}
