package com.valhallagame.traitserviceclient.message;

public enum TraitType {
	KICK,
	DODGE,
	FROST_BLAST,
	GUNGNIRS_WRATH,
	SOUL_TRANSFUSION,
	SHIELD_BASH,
	FROST_ARROWS,
	RECOVER,
	PETRIFY,
	NORTHERN_WINDS,
	SHIELD_BREAKER,
	HEMORRHAGE,
	COUNTERATTACK,
	TAUNT,
	FREYRS_PURGE,
	FRIGGS_INTERVENTION,
	SEIDHRING
}
