package com.valhallagame.traitserviceclient.message;

public enum TraitType {
	// GIFTS
	KICK,
	DODGE,
	FROST_BLAST,
	GUNGNIRS_WRATH,
	SOUL_TRANSFUSION,
	SHIELD_BASH,
	FROST_ARROWS,
	RECOVER,
	PETRIFY,
	SHIELD_BREAKER,
	HEMORRHAGE,
	PARRY,
	TAUNT,
	FIERY_PURGE,
	FRIGGS_INTERVENTION,
	SEIDHRING,
	ONEHANDED_SPECIALIZATION
}
